package com.nexusagent.query.application;

import java.util.List;
import java.util.stream.Collectors;

import com.nexusagent.context.domain.Citation;
import com.nexusagent.context.domain.ContextBuildResult;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

@Service
public class LocalTemplateAnswerGenerator implements AnswerGenerator {

    private static final int MAX_CONTEXT_SNIPPET_CHARS = 700;

    @Override
    public String name() {
        return "local-template";
    }

    @Override
    public Mono<GeneratedAnswer> generate(String question, ContextBuildResult context) {
        return Mono.fromSupplier(() -> generateNow(question, context));
    }

    private GeneratedAnswer generateNow(String question, ContextBuildResult context) {
        String limitations = "Generated by LocalTemplateAnswerGenerator, a local placeholder generator; no LLM was called.";
        if (context.finalContextText() == null || context.finalContextText().isBlank()) {
            return new GeneratedAnswer(
                    "LocalTemplateAnswerGenerator placeholder answer: insufficient retrieved context. I cannot provide a grounded answer for this question without cited context.",
                    name(),
                    List.of(
                            limitations,
                            "No retrieved context was available, so no grounded claims or citations were generated."
                    )
            );
        }

        String contextSnippet = collapseWhitespace(context.finalContextText());
        if (contextSnippet.length() > MAX_CONTEXT_SNIPPET_CHARS) {
            contextSnippet = contextSnippet.substring(0, MAX_CONTEXT_SNIPPET_CHARS) + "...";
        }
        String citationSummary = context.citations().stream()
                .map(this::citationSummary)
                .collect(Collectors.joining(", "));
        if (citationSummary.isBlank()) {
            citationSummary = "no citations";
        }

        String answer = """
                LocalTemplateAnswerGenerator placeholder answer: Based on the retrieved context, the relevant evidence is: %s

                Sources: %s
                """.formatted(contextSnippet, citationSummary).trim();
        return new GeneratedAnswer(
                answer,
                name(),
                List.of(limitations, "Replace this generator with a real ChatModel or answer service in a later milestone.")
        );
    }

    private String citationSummary(Citation citation) {
        return "%s %s".formatted(citation.citationMarker(), citation.originalFilename());
    }

    private String collapseWhitespace(String value) {
        return value.replaceAll("\\s+", " ").trim();
    }
}
